const chosen=new Set();let candidates=[],candidateIndex=0;
const $=s=>document.querySelector(s);
// The standalone preview returns to the portfolio in both hosted and file modes.
document.querySelectorAll('.back').forEach(a=>a.href='../index.html');
function orders(){document.querySelectorAll('[data-order]').forEach(b=>{const selected=chosen.has(Number(b.dataset.order));b.setAttribute('aria-pressed',String(selected));b.textContent=selected?'已点 · 再点取消':'点这道菜 ＋';});$('#order-count').textContent=chosen.size;const list=$('#order-list');list.replaceChildren();if(!chosen.size)list.textContent='还没有点菜，挑一道喜欢的吧。';for(const i of chosen){const b=document.createElement('button');b.type='button';b.textContent=menu[i].name+' ×';b.setAttribute('aria-label','移除'+menu[i].name);b.onclick=()=>{chosen.delete(i);orders();};list.append(b);}$('#clear-orders').disabled=!chosen.size;}
document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.order);chosen.has(i)?chosen.delete(i):chosen.add(i);orders();});$('#clear-orders').onclick=()=>{chosen.clear();orders();};
document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.photo),show=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(show));b.textContent=show?'看手绘封面 ↗':'看实拍 ↗';const img=$(`[data-image="${i}"]`);img.src=menu[i][show?'photo':'cover'];img.alt=menu[i].name+(show?'的成品实拍':'的手绘封面');});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#menu-panel').hidden=b.dataset.tab!=='menu';$('#store-panel').hidden=b.dataset.tab!=='store';});
function resetSuggestion(){candidates=[];candidateIndex=0;$('#recipe-title').textContent='先看看食材架';$('#recipe-description').textContent='选中食材后，点击“找一道菜”。';$('#recipe-source').textContent='';$('#next-recipe').disabled=true;}
function showRecipe(){const item=candidates[candidateIndex],available=new Set([...document.querySelectorAll('.ingredient input:checked')].map(x=>x.value));const missing=item.core.filter(x=>!available.has(x));$('#recipe-title').textContent=item.name;$('#recipe-description').textContent=missing.length?'还缺核心食材：'+missing.join('、')+'。可以补齐后再做。':'核心食材已经齐了：'+item.core.join('、')+'。调味料请按实际做法准备。';$('#recipe-source').textContent='CookLikeHOC · '+item.source+' · 候选 '+(candidateIndex+1)+' / '+candidates.length;$('#next-recipe').disabled=candidates.length<2;}
$('#match').onclick=()=>{const available=new Set([...document.querySelectorAll('.ingredient input:checked')].map(x=>x.value));if(!available.size){resetSuggestion();$('#recipe-description').textContent='先勾选至少一种食材。';return;}candidates=recipes.map(r=>({...r,score:r.core.filter(x=>available.has(x)).length})).filter(r=>r.score>0).sort((a,b)=>b.score-a.score);candidateIndex=0;if(!candidates.length){resetSuggestion();$('#recipe-description').textContent='这份演示菜谱中暂时没有匹配结果，请换几种食材。';return;}showRecipe();};
$('#next-recipe').onclick=()=>{if(candidates.length){candidateIndex=(candidateIndex+1)%candidates.length;showRecipe();}};
document.querySelectorAll('.ingredient input').forEach(x=>x.onchange=resetSuggestion);$('#clear-ingredients').onclick=()=>{document.querySelectorAll('.ingredient input').forEach(x=>x.checked=false);resetSuggestion();};orders();
